GET http://localhost:3000/user/2

###

GET http://localhost:3000/user/10

###

GET http://localhost:3000/user?name=un%20autre

###

GET http://localhost:3000/user?name=personne

###
GET http://localhost:3000/user

###

POST http://localhost:3000/user 
Content-Type: application/json

{
    "id":1,
    "name" : "un premier"
}

###

POST http://localhost:3000/user 
Content-Type: application/json

{
    "id":2,
    "name" : "un autre"
}

###

PUT http://localhost:3000/user 
Content-Type: application/json

{
    "id":1,
    "name" : "un premier maj"
}

###

PUT http://localhost:3000/user 
Content-Type: application/json

{
    "id":8,
    "name" : "un qui n'existe pas"
}


###

DELETE http://localhost:3000/user/1


###

DELETE http://localhost:3000/user/10